top_n_genomes_to_ingest : 300


micro_organisms :
  - "Escherichia coli"
   # - "Staphylococcus aureus"
   # - "Streptococcus pneumoniae"
   # - "Pseudomonas aeruginosa"
   # - "Klebsiella pneumoniae"
   # - "Clostridioides difficile"
   # - "Neisseria meningitidis"
   # - "Mycobacterium tuberculosis"
   

#This is to generate label file  
anti_biotics : 
  - "amoxicillin/clavulanic acid"
  - "amikacin"
  - "amoxicillin"
  - "ceftazidime"
  - "chloramphenicol"
  - "ciprofloxacin"
  - "cefepime"
  - "gentamicin"
  - "meropenem"
  - "tigecycline"
  
    
